# Generated by Django 5.1.2 on 2024-10-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employee_count', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
    ]
