# Generated by Django 5.1.2 on 2024-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_industry_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_count',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.TextField(default='No Address Provided'),
        ),
        migrations.AddField(
            model_name='company',
            name='current_employee_estimate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(default='unknown.com', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.CharField(default='https://linkedin.com', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='locality',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='size_range',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='total_employee_estimate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue',
            field=models.BigIntegerField(),
        ),
    ]
