# Generated by Django 4.2.2 on 2024-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_company_address_alter_company_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="year_founded",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
