# Generated by Django 4.2.2 on 2024-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0008_alter_company_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="address",
        ),
        migrations.AlterField(
            model_name="company",
            name="year_founded",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
